# DragonRise -> Xbox 360 mapping
# Generated automatically.
#
# Format:
# name=type,code,value,event_name
#
left_stick_x=abs,0,80,ABS_X
left_stick_y=abs,1,89,ABS_Y
right_stick_x=abs,3,94,ABS_RX
right_stick_y=abs,4,96,ABS_RY
l2=abs,2,218,ABS_Z
r2=key,313,1,KEY_313
dpad_left=abs,16,-1,ABS_HAT0X
dpad_right=abs,16,1,ABS_HAT0X
dpad_up=abs,17,-1,ABS_HAT0Y
dpad_down=abs,17,1,ABS_HAT0Y
a=key,304,1,KEY_304
b=key,305,1,KEY_305
x=key,308,1,KEY_308
y=key,307,1,KEY_307
l1=key,310,1,KEY_310
r1=key,311,1,KEY_311
back=key,314,1,KEY_314
start=key,315,1,KEY_315
guide=key,316,1,KEY_316
l3=key,317,1,KEY_317
r3=key,318,1,KEY_318
