# DragonRise -> Xbox 360 mapping
# Generated automatically.
#
# Format:
# name=type,code,value,event_name
#
left_stick_x=abs,0,0,ABS_X
left_stick_y=abs,1,90,ABS_Y
right_stick_x=abs,3,95,ABS_RX
right_stick_y=abs,5,77,ABS_RZ
l2=key,292,1,BTN_TOP2
r2=key,293,1,BTN_PINKIE
dpad_left=abs,16,-1,ABS_HAT0X
dpad_right=abs,16,1,ABS_HAT0X
dpad_up=abs,17,-1,ABS_HAT0Y
dpad_down=abs,17,1,ABS_HAT0Y
a=key,290,1,BTN_THUMB2
b=key,289,1,BTN_THUMB
x=key,291,1,BTN_TOP
y=key,288,1,BTN_TRIGGER
l1=key,294,1,BTN_BASE
r1=key,295,1,BTN_BASE2
back=key,296,1,BTN_BASE3
start=key,297,1,BTN_BASE4
guide=disabled
l3=key,298,1,BTN_BASE5
r3=key,299,1,BTN_BASE6
